create sequence hibernate_sequence start 1 increment 1;
create table col_combine (id int8 not null, col_name varchar(255), col_num int4 not null, column_type varchar(255), key boolean not null, output_type int4, primary key (id));
create table col_lookup (id int8 not null, col_name varchar(255), col_num int4 not null, column_type varchar(255), key boolean not null, output_type int4, primary key (id));
create table col_metadata (id int8 not null, primary key (id));
create table col_metadata_columns (column_metadata_id int8 not null, columns_id int8 not null, primary key (column_metadata_id, columns_id));
create table col_simple (id int8 not null, col_name varchar(255), col_num int4 not null, column_type varchar(255), key boolean not null, output_type int4, primary key (id));
create table col_weeknum (id int8 not null, col_name varchar(255), col_num int4 not null, column_type varchar(255), key boolean not null, output_type int4, primary key (id));
create table column_def_inputs (column_definition_id int8 not null, inputs_id int8 not null, primary key (column_definition_id, inputs_id));
create table filter_contains (id int8 not null, primary key (id));
create table filter_def_inputs (filter_definition_id int8 not null, inputs_id int8 not null, primary key (filter_definition_id, inputs_id));
create table filter_metadata (id int8 not null, primary key (id));
create table filter_metadata_filters (filter_metadata_id int8 not null, filters_id int8 not null, primary key (filter_metadata_id, filters_id));
create table filter_numeric (id int8 not null, primary key (id));
create table lookup_pairs (id int8 not null, key varchar(255), value varchar(255), primary key (id));
create table lookups (id int8 not null, name varchar(255), primary key (id));
create table lookups_values (lookup_id int8 not null, values_id int8 not null, primary key (lookup_id, values_id));
create table metadata_pairs (id int8 not null, key varchar(255), value varchar(255), primary key (id));
create table report_metadata (id int8 not null, data_source varchar(255), reduction_type int4, report_name varchar(255), cols_id int8, filter_id int8, primary key (id));
create table user_profile (id int8 not null, apikey varchar(255), enabled boolean not null, password varchar(255), username varchar(255), primary key (id));
alter table if exists col_metadata_columns add constraint UK_kfmyfg3tvt31s6vfgn7cq138x unique (columns_id);
alter table if exists column_def_inputs add constraint UK_tanhdlfbmd4aa3tp0k0xjufxv unique (inputs_id);
alter table if exists filter_def_inputs add constraint UK_a0ujj1jxjobi8hhkgnh556ohn unique (inputs_id);
alter table if exists filter_metadata_filters add constraint UK_5jn1h4wrviiy93s82op47uiwy unique (filters_id);
alter table if exists lookups_values add constraint UK_p946jckdwkbdb65j5usxr6mj2 unique (values_id);
alter table if exists col_metadata_columns add constraint FKoqrbdsu11px2ph4qvt1uscx1k foreign key (column_metadata_id) references col_metadata;
alter table if exists column_def_inputs add constraint FKh2dh2gaym352d3hg8hqclm7dv foreign key (inputs_id) references metadata_pairs;
alter table if exists filter_def_inputs add constraint FKl2vm9pm4rapg2n2si1rv8dk33 foreign key (inputs_id) references metadata_pairs;
alter table if exists filter_metadata_filters add constraint FK1coum5ug38lv048lkexc21vg2 foreign key (filter_metadata_id) references filter_metadata;
alter table if exists lookups_values add constraint FKdr6hbvjl3ihvhks3lw87ebo9n foreign key (values_id) references lookup_pairs;
alter table if exists lookups_values add constraint FK66xfy5m1etsvdbsqtq1l8dk9i foreign key (lookup_id) references lookups;
alter table if exists report_metadata add constraint FKbweo5r5426a1q09v81qkou5ij foreign key (cols_id) references col_metadata;
alter table if exists report_metadata add constraint FK99n2k3cu7ejgu606nab5rne6a foreign key (filter_id) references filter_metadata;
insert into user_profile (apikey, enabled, password, username, id) values ('update API key in gui!','t','$2a$11$s1LayP.Oqb0srgx.bWBBoO8EjSBiMtCaozx.iJHRhfYprjdJdu4/i','admin',1);